### ISSUE TITLE
Export Code Coverage Data (Feature Suggestion) 

### ISSUE THREAD

**Issue by rafasashi** [luisfarzati/chromda#17]
Is there any way to alter chromda to capture the Code Coverage Data?

https://stackoverflow.com/questions/45106841/chrome-devtools-coverage-how-to-save-or-capture-code-used-code/54983240#54983240

It would be amazing to extract none critical CSS and JS programmatically for page speed optimization.

**Comment by rafasashi** [comment]
A more generic approach could be to pass Chrome commands and replace the image data by the console logs in the output file.

**Comment by lufzle** [comment]
Hi @rafasashi, apparently Puppeteer supports this: https://philkrie.me/2018/07/04/extracting-coverage.html

For this you'll need to fork [MrPuppetshot](https://github.com/luisfarzati/mrpuppetshot), which is a library Chromda uses internally, and add the coverage logic in the [navigate method](https://github.com/luisfarzati/mrpuppetshot/blob/master/src/MrPuppetShot.js#L28).

Snippet taken from the blog post above:

```js
   await Promise.all([
        page.coverage.startJSCoverage(),
        page.coverage.startCSSCoverage()
    ]);

    await page.goto('https://www.google.com');
  
    //Retrive the coverage objects
    const [jsCoverage, cssCoverage] = await Promise.all([
        page.coverage.stopJSCoverage(),
        page.coverage.stopCSSCoverage(),
    ]);
```

If you prefer a quick hack just to see if it works, you could also replace [the logic in Chromda where it performs browser navigation](https://github.com/luisfarzati/chromda/blob/master/src/captureScreenshot.js#L89) with something like this:

```js
const rawBrowser = await browser.browser;
const page = await rawBrowser.newPage();

await Promise.all([
    page.coverage.startJSCoverage(),
    page.coverage.startCSSCoverage()
]);

await page.goto(options.url, options.puppeteer?.navigation);
  
//Retrive the coverage objects
const [jsCoverage, cssCoverage] = await Promise.all([
    page.coverage.stopJSCoverage(),
    page.coverage.stopCSSCoverage(),
]);

browser.page = page;
```

**Comment by rafasashi** [comment]
Thank you for your insight @luisfarzati 

I confirm that your quick hack retrieves the js and css coverage, it is really amazing!

**Comment by rafasashi** [comment]
I would like to perform more testing regarding this implementation however the lambda function is compiled and right now I am re-deploying the changes every time ( which is probably not the fastest way to work ).

I have also tried to run the app locally via `node src/captureScreenshot.js` but I get some syntax error:

```
  new URL(options?.url);
                  ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

```

Could you please guide me regarding the proper dev and testing method? Perhaps you know a parameter to deploy only the captureScreenshot.js file and leave the rest as it is.
